[package]
name = "cloud-sdk"
version = "0.3.12"
authors = ["support@tensorlake.ai"]
description = "A Rust SDK for interacting with Tensorlake Cloud APIs."
license = "Apache-2.0"
edition = "2024"

[dependencies]
miette = "7.6.0"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
serde_repr = "^0.1"
serde_with = { version = "^3.8", default-features = false, features = ["base64", "std", "macros"] }
url = "^2.5"
reqwest = { version = "^0.12", default-features = false, features = ["json", "multipart", "rustls-tls"] }

[dev-dependencies]
httpmock = "0.7"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[lints.clippy]
too_many_arguments = "allow"
